### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by rajam1215** [exozet/Geolocator#18] opened 2022-04-20 06:04 UTC
Hello @kibotu

In new android 12 version this error is occur dew to pending intent  message log show this 

java.lang.IllegalArgumentException: : Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
        at com.sprotte.geolocator.tracking.LocationTracker.getTrackingPendingIntent(LocationTracker.kt:32)
        at com.sprotte.geolocator.tracking.LocationTracker.requestLocationUpdates(LocationTracker.kt:93)
        at com.sprotte.geolocator.tracking.LocationTracker.requestLocationUpdates(LocationTracker.kt:68)
        at com.royalways.montecarloretail.activity.LoginActivity$3.onResponse(LoginActivity.java:314)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
        
        my some R&D show this code 
        
         val updatedPendingIntent = PendingIntent.getActivity(
        applicationContext,
        NOTIFICATION_REQUEST_CODE,
        updatedIntent,
        PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT // setting the mutability flag 
        )

Since you are using AlarmManager you should be able to use the IMMUTABLE flag.
     
Please look in to it.

thanks

**Comment by kibotu** [comment] 2022-04-20 06:48
Thanks for the info. Will have a look

**Comment by rajam1215** [comment] 2022-04-20 09:58
@kibotu please check it is appreciable, if you have time please make it quick, coz I use your lib in live app. in live app this type of error occur

Thanks

**Comment by rajam1215** [comment] 2022-04-22 05:53
@kibotu there is issue in the library, and it is occur in live app, please look in to it.

**Comment by rajam1215** [comment] 2022-04-26 04:40
@kibotu please look in to it, or other wise, I have to switch on other alternative,

**Comment by kibotu** [comment] 2022-04-26 07:12
we're accepting PRs

**Comment by rajam1215** [comment] 2022-04-26 07:50
> we're accepting PRs

@kibotu

Just add this line **PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT** in **LocationTracker.Kt** class

this is the method in your **LocationTracker** class, there is only one pending intent type that is **PendingIntent.FLAG_UPDATE_CURRENT** just copy past with the above line.

      private fun getTrackingPendingIntent(context: Context): PendingIntent {
      val intent = Intent(context, LocationTrackerUpdateBroadcastReceiver::class.java)
      intent.action = LocationTrackerUpdateBroadcastReceiver.ACTION_PROCESS_UPDATES
      return PendingIntent.getBroadcast(
        context,
        REQUEST_CODE,
        intent,
        PendingIntent.FLAG_UPDATE_CURRENT
      )
     }
Except you don't need to do anything, it is new feature for android 12, but library is read only, so I can't change this thing from my end. after the change please update the library, that is it. please do it, it will be appreciable.

Thanks

**Comment by rajam1215** [comment] 2022-04-27 07:28
@kibotu which kind of difficulty you face right now, means you take so much time to solve this minor issue, I didn't understand what you want, this is your library, and you accept **pull request** you can do this thing in your side easily, or give me the authority to make change in that, so issue will solve and user can use your lib without any errors.

**Comment by kibotu** [comment] 2022-04-27 11:57
Dear [rajam1215](https://github.com/rajam1215),

Thank you for your feedback. 

The issue is being resolved in [latest 2.0.0 release](https://jitpack.io/#exozet/Geolocator) 


Another general topic:

Please consider rethinking your tone and demands for an open source project like this. However we don't work for you. 

I assume you want to participate in [open source](https://en.wikipedia.org/wiki/Open_source) and want to learn about it since you haven't shared a single line of code on Github yourself yet.

A great start is on the official Github documentation:

[How to create pull request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request)

here another good [step by step guide how to contribute](https://www.dataschool.io/how-to-contribute-on-github/)

Sincerely every open source project maintainer on the internet.

**Closed as completed by kibotu** 2022-04-27 11:57 UTC
Labels: help wanted

**Comment by rajam1215** [comment] 2022-04-27 12:33
> Dear [rajam1215](https://github.com/rajam1215),
> 
> Thank you for your feedback.
> 
> The issue is being resolved in [latest 2.0.0 release](https://jitpack.io/#exozet/Geolocator)
> 
> Another general topic:
> 
> Please consider rethinking your tone and demands for an open source project like this. However we don't work for you.
> 
> I assume you want to participate in [open source](https://en.wikipedia.org/wiki/Open_source) and want to learn about it since you haven't shared a single line of code on Github yourself yet.
> 
> A great start is on the official Github documentation:
> 
> [How to create pull request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request)
> 
> here another good [step by step guide how to contribute](https://www.dataschool.io/how-to-contribute-on-github/)
> 
> Sincerely every open source project maintainer on the internet.
Hello @kibotu 

I really apologies if you think my tone is not good, I appreciate that, you work on issue in your busy schedule of work, I am glad to learn how to maintain open source project in github, really I don't have much knowledge about maintain of open source project in github

Thanks for the links.
Bishal Malick
