### ISSUE TITLE
In Android 12, 13, 14 Background Location not working

### ISSUE THREAD

**Issue by rajam1215** [exozet/Geolocator#34] opened 2024-01-16 11:31 UTC
@kibotu @khalid64927 

In android 12, 13, 14 background locations not working not even foreground, Already ask permission in my code I also ask background permission and send user in setting screen to click on "**Allow all the time**", with all this things still library not getting background location not even foreground, please look in to it.

Thanks

**Comment by khalid64927** [comment] 2024-01-17 07:24
In foreground I can see its working and I can see the Notification. But, I do see Geofence Broadcast is not being triggered when app is in BG or killed, Strange. I will look into this later over the weekend.

**Comment by rajam1215** [comment] 2024-01-17 07:49
@khalid64927 
But when use the same **Read.MD** documentation in my code, it is not working, can you share the **notification code and permission code for java** for the library, I already ask Permissions from user at my side code, with this library not working, but notification code is not there in MD file, can  you look in to it, i thing for notification code, it is not working.

**Comment by rajam1215** [comment] 2024-01-20 11:02
@khalid64927 can you set Read.MD file with notification code

**Comment by khalid64927** [comment] 2024-01-20 15:36
It's a minor check that happens at the very first. I will add that in readme. 

Meanwhile, you can refer the [app module](https://github.com/kibotu/geofencer/blob/master/app/src/main/java/com/sprotte/geolocator/demo/kotlin/MapFragment.kt#L206). 

Can you try and see, if you are not getting geofence alert in app module as well ?

**Comment by khalid64927** [comment] 2024-03-11 08:19
@rajam1215  can you close this issue if you are not able to reproduce anymore.

**Closed as completed** 2024-12-07 11:42 UTC
